version: '3.8'

services:
  user-app:
    restart: always
    build: ./
    depends_on:
      - db
      - cache
    ports:
      - 50051:50051
    environment:
      - DB_PASSWORD=postgres
    links:
      - db
    networks:
      - user-networks
  db:
    restart: always
    image: postgres:latest
    volumes:
        - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - user-networks
  cache:
    restart: always
    image: redis:6.2.6
    ports:
      - 6379:6379
    networks:
      - user-networks

networks:
  user-networks: