version: '3.8'

services:
  user-app:
    restart: always
    build: ./
    depends_on:
      - db
      - cache
    ports:
      - 50051:50051
    environment:
      - DB_PASSWORD=userdb
    links:
      - db
    networks:
      - user-networks

  db:
    restart: always
    image: postgres:latest
    volumes:
        - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userdb
    ports:
      - 5432:5432
    networks:
      - user-networks

  cache:
    restart: always
    image: redis:6.2.6
    command: ./redis-server
    ports:
      - 6379:6379
    networks:
      - user-networks

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - user-networks
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - user-networks

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local 
  
networks:
  user-networks: