grpc:
  host: "localhost"
  port: 50051

db:
  host: "db"
  port: 5432
  user: "postgres"
  dbname: "postgres"
  
redis:
  host: "cache"
  port: 6379
  passwd: ""

clickhouse:
  host: "click"
  port: 9000
  password: ""
  username: "default"
  db: "default"

kafka:
  addr: "kafka:9094"
  topic: "users"
  consumer-group: "users"
  consumer-num: 1
  addr-click: "kafka:9092"
  partition-num: 2
  format: "JSONEachRow"
